//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSoapBancos.servicioDavivienda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioDavivienda.IServidorSoapDavivienda")]
    public interface IServidorSoapDavivienda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/consultaRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/consultaRecaudoResponse")]
        string consultaRecaudo(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/consultaRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/consultaRecaudoResponse")]
        System.Threading.Tasks.Task<string> consultaRecaudoAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/notificacionRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/notificacionRecaudoResponse")]
        string notificacionRecaudo(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/notificacionRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/notificacionRecaudoResponse")]
        System.Threading.Tasks.Task<string> notificacionRecaudoAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/reversionNotificacionRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/reversionNotificacionRecaudoResponse")]
        string reversionNotificacionRecaudo(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServidorSoapDavivienda/reversionNotificacionRecaudo", ReplyAction="http://tempuri.org/IServidorSoapDavivienda/reversionNotificacionRecaudoResponse")]
        System.Threading.Tasks.Task<string> reversionNotificacionRecaudoAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServidorSoapDaviviendaChannel : ClienteSoapBancos.servicioDavivienda.IServidorSoapDavivienda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServidorSoapDaviviendaClient : System.ServiceModel.ClientBase<ClienteSoapBancos.servicioDavivienda.IServidorSoapDavivienda>, ClienteSoapBancos.servicioDavivienda.IServidorSoapDavivienda {
        
        public ServidorSoapDaviviendaClient() {
        }
        
        public ServidorSoapDaviviendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServidorSoapDaviviendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorSoapDaviviendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorSoapDaviviendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string consultaRecaudo(int value) {
            return base.Channel.consultaRecaudo(value);
        }
        
        public System.Threading.Tasks.Task<string> consultaRecaudoAsync(int value) {
            return base.Channel.consultaRecaudoAsync(value);
        }
        
        public string notificacionRecaudo(int value) {
            return base.Channel.notificacionRecaudo(value);
        }
        
        public System.Threading.Tasks.Task<string> notificacionRecaudoAsync(int value) {
            return base.Channel.notificacionRecaudoAsync(value);
        }
        
        public string reversionNotificacionRecaudo(int value) {
            return base.Channel.reversionNotificacionRecaudo(value);
        }
        
        public System.Threading.Tasks.Task<string> reversionNotificacionRecaudoAsync(int value) {
            return base.Channel.reversionNotificacionRecaudoAsync(value);
        }
    }
}
